# Generated by Django 4.1.3 on 2022-12-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, null=True, verbose_name='Likes'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
